const menu = [
  {
    id: 1,
    title: "popcorn chicken rice",
    category: "rice dishes",
    price: 14,
    img: "./images/test.jpeg",
    desc: " Choose from mild, medium, hot, or no spice Tender bites of dark meat breaded, fried, and seasoned with pepper salt.",
  },
  {
    id: 2,
    title: "Jalapeño Gravy",
    category: "rice dishes",
    price: 15,
    img: "./images/test.jpeg",
    desc: "- Choice of chicken or beef Homemade jalapeño gravy containing carrot, onion, jalapeño, assorted greens, and meat.",
  },
  {
    id: 3,
    title: "stir-fried udon",
    category: "Dry Noodles",
    price: 15,
    img: "./images/test.jpeg",
    desc: "  Choose from pork or chicken Udon noodles with carrot, onion, and assorted greens.",
  },
  {
    id: 4,
    title: "shrimp fried rice",
    category: "fried rice",
    price: 15,
    img: "./images/test.jpeg",
    desc: "",
  },
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
];
export default menu;